services:
    app:
        build:
            context: docker
            dockerfile: Dockerfile
        container_name: tenant_app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker/php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - tenant

    db:
        image: mariadb:latest
        container_name: tenant_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - "3304:3306"
        volumes:
            - ./docker/dbdata:/var/lib/mysql
        networks:
            - tenant

    nginx:
        image: nginx:latest
        container_name: tenant_nginx
        restart: unless-stopped
        ports:
            - "8002:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - tenant
networks:
    tenant:
        driver: bridge

